### ISSUE TITLE
Containerlab 2 nodes setup

### ISSUE THREAD

**Issue by minminlittleshrimp** [minminlittleshrimp/acn_lab#3]

**Comment by minminlittleshrimp** [comment]
Create topology.yml:
```
name: PPPoE

topology:
  nodes:
    node1:
      kind: linux
      image: acnlab
      exec:
          - apt-get update
          - apt-get install -y pppoe pppoeconf
    node2:
      kind: linux
      image: acnlab
      exec:
          - apt-get update
          - apt-get install -y pppoe pppoeconf

  links:
    - endpoints: ["node1:eth1", "node2:eth1"]
```

Run to deploy:
```
 sudo containerlab deploy --topo topology.yml
```
